title: donghee89's Blog
subtitle: Web Developer
description: La bendición de dios
author: donghee89
email: sms44556688@gmail.com
avatar: assets/images/heebro.jpg

baseurl: "" # the subpath of your site, e.g. /blog
url: "https//:donghee1.github.io" # the base hostname & protocol for your site
remote_theme : jekyll-theme-prologue
# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]
